run: '180614_SN737_0438_BCC7MCACXX'

directions:
  - 'R1'
  - 'R2'

emails:
  demultiplexreport: "stefan.m.janssen@gmail.com"
  backup_validated: "stefan.m.janssen@gmail.com"

name_program: "spike"

dirs:
  prefix: "/data/Spike_data/"

  intermediate: "Intermediate/"
  inputs: "Inputs/"
  aggregation: "Aggregation/"
  reports: "Reports/"
  checks: "Checks/"
  references: "References/"

  samplesheets: "SampleSheets/"
  rawillumina: "Raw_Illumina/"
  benchmarks: "Benchmarks/"
  logs: "Logs/"

stepnames:
  backup_compress: "01_backup_compress"
  backup_transfer: "02_backup_transfer"
  backup_validate: "03_backup_validate"

  demultiplex: "05_demultiplex"
  rejoin_samples: "10_rejoin_samples"
  trim: "15_trim"
  xenograft_bwa_aln: "22_xenograft_bwa_aln"
  xenograft_bwa_sampe: "23_xenograft_bwa_sampe"
  xenograft_check: "24_xenograft_check"
  map: "25_map"
  nodup: "30_remove_pcr_duplicates"
  gatk_RealignerTargetCreator: "35_gatk_RealignerTargetCreator"
  gatk_IndelRealigner: "40_gatk_IndelRealigner"
  gatk_BaseRecalibrator: "45_gatk_BaseRecalibrator"
  gatk_PrintReads: "50_gatk_PrintReads"
  gatk_HaplotypeCaller: "55_gatk_HaplotypeCaller"
  gatk_SelectVariants: "60_gatk_SelectVariants"
  gatk_VariantRecalibrator: "65_gatk_VariantRecalibrator"
  gatk_ApplyRecalibration: "70_gatk_ApplyRecalibration"
  gatk_VariantFiltration: "75_gatk_VariantFiltration"
  gatk_CombineVariants: "80_gatk_CombineVariants"
  platypus: "85_platypus"
  platypus_filtered: "90_platypus_filtered"
  exome_coverage: "95_exome_coverage"
  #gatk_DepthOfCoverage: "95_gatk_DepthOfCoverage"

  # trio
  varscan_trio: "100_varscan_trio"
  varscan_filter: "105_varscan_filter"
  bam_readcount: "110_bam_readcount"
  varscan_fpfilter: "115_varscan_fpfilter"
  correct_genotypes: "120_correct_genotypes"
  merge_vcfs: "125_merge_vcfs"
  writing_headers: "130_writing_headers"

  # somatic
  samtools_mpileup: "135_samtools_mpileup"
  freec: "140_freec"
  mutect: "145_mutect"
  varscan_somatic: "150_varscan_somatic"
  varscan_processSomatic: "155_varscan_processSomatic"
  bam_readcount_somatic: "160_bam_readcount_somatic"

  somatic_FPfilter: "165_somatic_FPfilter"
  somatic_reduce: "170_somatic_reduce"
  vcf_annotate: "175_vcf_annotate"
  merge_somatic: "180_merge_somatic"

gatk:
  HaplotypeCallerQualityArguments: " -stand_call_conf 50.0 -stand_emit_conf 50.0 "

backup:
  username: "SeqUser"
  host: '10.2.5.12'
  targetdirectory: "array1/Sequencing_Backups/Illumina_HiSeq"

xenograft:
  references:
    mus musculus: 'GRCm'
    homo sapiens: 'GRCh'

references:
  genomes:
    homo sapiens: 'hGRC37.fa'
    mus musculus: 'Mus_musculus.GRCm38.71.dna.fa'
  knowns:
    homo sapiens:
      - file: "Mills_and_1000G_gold_standard.indels.b37.vcf"
        VariantRecalibrator: "--resource:mills,known=true,training=true,truth=true,prior=12.0"
        VariantRecalibrator_SNP: "--resource:mills,VCF,known=false,training=true,truth=true,prior=12.0"
      - file: "1000G_phase1.indels.b37.vcf"
        VariantRecalibrator: "--resource:1000G,known=false,training=true,truth=false,prior=10.0"
    mus musculus:
      - file: "C57BL6NJ_CBAJDBA2.indels.vcf.gz"
        VariantRecalibrator: "???"

# variables that can directly be overwritten from CML
pwd_backup: "thisisasecret"
num_threads: 16
