run: '180614_SN737_0438_BCC7MCACXX'

emails_demultiplexreport: "stefan.m.janssen@gmail.com"

name_program: "spike"

dirs:
  intermediate: "Intermediate/"
  inputs: "Inputs/"
  aggregation: "Aggregation/"
  reports: "Reports/"
  checks: "Checks/"

  samplesheets: "SampleSheets/"
  rawillumina: "Raw_Illumina/"
  benchmarks: "Benchmarks/"
  logs: "Logs/"

stepnames:
  demultiplex: "05_demultiplex"
  rejoin_samples: "10_rejoin_samples"
