run: '180614_SN737_0438_BCC7MCACXX'

directions:
  - 'R1'
  - 'R2'

emails_demultiplexreport: "stefan.m.janssen@gmail.com"

name_program: "spike"

dirs:
  prefix: "/data/Spike_data/"

  intermediate: "Intermediate/"
  inputs: "Inputs/"
  aggregation: "Aggregation/"
  reports: "Reports/"
  checks: "Checks/"
  references: "References/"

  samplesheets: "SampleSheets/"
  rawillumina: "Raw_Illumina/"
  benchmarks: "Benchmarks/"
  logs: "Logs/"

stepnames:
  demultiplex: "05_demultiplex"
  rejoin_samples: "10_rejoin_samples"
  trim: "15_trim"
  map: "25_map"
  nodup: "30_remove_pcr_duplicates"
  gatk_RealignerTargetCreator: "35_gatk_RealignerTargetCreator"
  gatk_IndelRealigner: "40_gatk_IndelRealigner"
  gatk_BaseRecalibrator: "45_gatk_BaseRecalibrator"
  gatk_PrintReads: "50_gatk_PrintReads"
  gatk_HaplotypeCaller: "55_gatk_HaplotypeCaller"
  gatk_SelectVariants: "60_gatk_SelectVariants"
  gatk_VariantRecalibrator: "65_gatk_VariantRecalibrator"
  gatk_ApplyRecalibration: "70_gatk_ApplyRecalibration"
  gatk_VariantFiltration: "75_gatk_VariantFiltration"
  gatk_CombineVariants: "80_gatk_CombineVariants"
  platypus: "85_platypus"
  platypus_filtered: "90_platypus_filtered"
  gatk_DepthOfCoverage: "95_gatk_DepthOfCoverage"
  varscan_mpileup: "100_varscan_mpileup"

gatk:
  HaplotypeCallerQualityArguments: " -stand_call_conf 50.0 -stand_emit_conf 50.0 "
