run: '180614_SN737_0438_BCC7MCACXX'

directions:
  - 'R1'
  - 'R2'
endings_bwa:
  - '.fa'
  - '.dict'
  - '.fa.amb'
  - '.fa.ann'
  - '.fa.bwt'
  - '.fa.fai'
  - '.fa.pac'
  - '.fa.sa'

mail_attachment_parameter: "-A"

emails:
  demultiplexreport: "stefan.m.janssen@gmail.com"
  backup_validated: "stefan.m.janssen@gmail.com"

name_program: "spike"

dirs:
  prefix: "/data/Spike_data/"
  tmpdir: "/data/tmp/"

  intermediate: "Intermediate/"
  inputs: "Inputs/"
  aggregation: "Aggregation/"
  reports: "Reports/"
  checks: "Checks/"
  references: "References/"

  samplesheets: "SampleSheets/"
  rawillumina: "Raw_Illumina/"
  persamplefastq: "PerSampleFastq/"
  benchmarks: "Benchmarks/"
  logs: "Logs/"

stepnames:
  backup_compress: "01_backup_compress"
  backup_transfer: "02_backup_transfer"
  backup_validate: "03_backup_validate"

  demultiplex: "05_demultiplex"
  rejoin_samples: "10_rejoin_samples"
  trim: "15_trim"
  xenograft_bwa_aln: "22_xenograft_bwa_aln"
  xenograft_bwa_sampe: "23_xenograft_bwa_sampe"
  xenograft_check: "24_xenograft_check"
  map: "25_map"
  nodup: "30_remove_pcr_duplicates"
  gatk_RealignerTargetCreator: "35_gatk_RealignerTargetCreator"
  gatk_IndelRealigner: "40_gatk_IndelRealigner"
  gatk_BaseRecalibrator: "45_gatk_BaseRecalibrator"
  gatk_PrintReads: "50_gatk_PrintReads"
  gatk_HaplotypeCaller: "55_gatk_HaplotypeCaller"
  gatk_SelectVariants: "60_gatk_SelectVariants"
  gatk_VariantRecalibrator: "65_gatk_VariantRecalibrator"
  gatk_ApplyRecalibration: "70_gatk_ApplyRecalibration"
  gatk_VariantFiltration: "75_gatk_VariantFiltration"
  gatk_CombineVariants: "80_gatk_CombineVariants"
  platypus: "85_platypus"
  platypus_filtered: "90_platypus_filtered"
  exome_coverage: "95_exome_coverage"
  #gatk_DepthOfCoverage: "95_gatk_DepthOfCoverage"

  # trio
  varscan_trio: "100_varscan_trio"
  varscan_filter: "105_varscan_filter"
  bam_readcount: "110_bam_readcount"
  varscan_fpfilter: "115_varscan_fpfilter"
  correct_genotypes: "120_correct_genotypes"
  merge_vcfs: "125_merge_vcfs"
  writing_headers: "130_writing_headers"

  # somatic
  samtools_mpileup: "135_samtools_mpileup"
  freec: "140_freec"
  mutect: "145_mutect"
  varscan_somatic: "150_varscan_somatic"
  varscan_processSomatic: "155_varscan_processSomatic"
  bam_readcount_somatic: "160_bam_readcount_somatic"

  somatic_FPfilter: "165_somatic_FPfilter"
  somatic_reduce: "170_somatic_reduce"
  vcf_annotate: "175_vcf_annotate"
  merge_somatic: "180_merge_somatic"

gatk:
  HaplotypeCallerQualityArguments: " -stand_call_conf 50.0 -stand_emit_conf 50.0 "

backup:
  username: "SeqUser"
  host: '10.2.5.12'
  targetdirectory: "array1/Sequencing_Backups/Illumina_HiSeq"

xenograft:
  references:
    mus musculus: 'GRCm'
    homo sapiens: 'GRCh'


projects:
  Alps:
    actions:
      - background
      - trio
    species: homo sapiens
  Fischer_Geron:
    actions:
      - background
      - tumornormal
    species: homo sapiens
    xenograft: "GRCh_GRCm_filtering_hybrid.fa"
  Maus_Hauer:
    actions:
      - background
      - tumornormal
    species: mus musculus
  AG_Remke:
    actions:
      - demultiplex
  Keimbahn:
    actions:
      - background
      - tumornormal
    species: homo sapiens
  ALL_family_LB:
    actions:
      - persamplefastq
      - background
      - trio
    species: homo sapiens
    exometrack:
      file: "Agilent_SureSelect_Human_AllExon_V6_r2.hGRC37.Covered.bed"
      protocol_name: "SureSelectHumanAllExonV6r2"
    fastq:
      forward: '_1'
      reverse: '_2'

references:
  genomes:
    homo sapiens:
      file: 'hGRC37'  # without .fa!
      lengths: 'hGRC37.len'
      gemMappabilityFile: 'hGRC37.mappability.mappability'
      chromosomes:
        - "hGRC37_chromosomes/1.fa"
        - "hGRC37_chromosomes/2.fa"
        - "hGRC37_chromosomes/3.fa"
        - "hGRC37_chromosomes/4.fa"
        - "hGRC37_chromosomes/5.fa"
        - "hGRC37_chromosomes/6.fa"
        - "hGRC37_chromosomes/7.fa"
        - "hGRC37_chromosomes/8.fa"
        - "hGRC37_chromosomes/9.fa"
        - "hGRC37_chromosomes/10.fa"
        - "hGRC37_chromosomes/11.fa"
        - "hGRC37_chromosomes/12.fa"
        - "hGRC37_chromosomes/13.fa"
        - "hGRC37_chromosomes/14.fa"
        - "hGRC37_chromosomes/15.fa"
        - "hGRC37_chromosomes/16.fa"
        - "hGRC37_chromosomes/17.fa"
        - "hGRC37_chromosomes/18.fa"
        - "hGRC37_chromosomes/19.fa"
        - "hGRC37_chromosomes/20.fa"
        - "hGRC37_chromosomes/21.fa"
        - "hGRC37_chromosomes/22.fa"
        - "hGRC37_chromosomes/X.fa"
        - "hGRC37_chromosomes/Y.fa"
      SNPfile: "hg19_deCHRd_snp137.SingleDiNucl.1based.txt"
      cosmic: "CosmicCodingMuts_v63_300113.vcf"
    mus musculus:
      file: 'Mus_musculus.GRCm38.71.dna'  # without .fa!
      lengths: 'GRCm38.71.len'
      gemMappabilityFile: 'Mus_musculus.GRCm38.71.dna.fa.index.gem.mappability.mappability'
      chromosomes:
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.1.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.2.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.3.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.4.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.5.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.6.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.7.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.8.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.9.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.10.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.11.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.12.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.13.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.14.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.15.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.16.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.17.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.18.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.19.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.X.fa"
        - "GRCm38.71_chromosomes/Mus_musculus.GRCm38.71.dna.chromosome.Y.fa"
      SNPfile: "UCSC_mm10_dechr_reorder_nomult_sort_for_freec.txt"
      cosmic:
  knowns:
    homo sapiens:
      - file: "Mills_and_1000G_gold_standard.indels.b37.vcf"
        RealignerTargetCreator: "yes"
        BaseRecalibrator: 'yes'
        VariantRecalibrator_SNP: "mills,VCF,known=false,training=true,truth=true,prior=12.0"
        VariantRecalibrator_INDEL: "mills,known=true,training=true,truth=true,prior=12.0"

      - file: "1000G_phase1.indels.b37.vcf"
        RealignerTargetCreator: "yes"
        BaseRecalibrator: 'yes'
        VariantRecalibrator_INDEL: "1000G,known=false,training=true,truth=false,prior=10.0"

      - file: "hapmap_3.3.b37.vcf"
        VariantRecalibrator_SNP: "hapmap,VCF,known=false,training=true,truth=true,prior=12.0"

      - file: "1000G_phase1.snps.high_confidence.b37.vcf"
        VariantRecalibrator_SNP: "omni,VCF,known=false,training=true,truth=false,prior=10.0"

      - file: "1000G_omni2.5.b37.vcf"
        VariantRecalibrator_SNP: "omni,VCF,known=false,training=true,truth=false,prior=12.0"

      - file: "dbSNP135_GRCh37.3.vcf"
        BaseRecalibrator: 'yes'
        mutect:

      - file: "dbsnp_138.b37.vcf"
        BaseRecalibrator: 'yes'
        VariantRecalibrator_SNP: "dbsnp,VCF,known=true,training=false,truth=false,prior=2.0"
    mus musculus:
      - file: "C57BL6NJ_CBAJDBA2.indels.vcf.gz"
        RealignerTargetCreator: "yes"
        BaseRecalibrator: 'yes'
        VariantRecalibrator_INDEL: "mgpindels,known=true,training=true,truth=true,prior=12.0"

      - file: "Mus_musculus.ref_clean.vcf.gz.recode.vcf.gz"
        BaseRecalibrator: 'yes'
        VariantRecalibrator_SNP: "mouse_dbsnp,VCF,known=true,training=true,truth=false,prior=8.0"
        mutect:

      - file: "C57BL6NJ.genoc5.ref.snp.vcf.gz.recode.vcf.gz"
        VariantRecalibrator_SNP: "C58BL6NJ_snps,VCF,known=false,training=true,truth=true,prior=12.0"

      - file: "CBAJDBA2.genoc7.ref.snp.recode.vcf.gz"
        VariantRecalibrator_SNP: "CBAJDBA2_snps,VCF,known=false,training=true,truth=true,prior=12.0"
  exometrack:
    homo sapiens:
      file: "Agilent_SureSelect_V5plusUTR.bed"
      protocol_name: "SureSelectXTV5plusUTRautomated"
    mus musculus:
      file: "Agilent_mouseexome_S0276129_Regions_mm10_modified_merged.bed"
      protocol_name: "SureSelectXTmouse"
  varscan_somatic:
    homo sapiens: " --min-coverage-normal 8 --min-coverage-tumor 10 --min-reads 4 "
    mus musculus: " --min-coverage-normal 6 --min-coverage-tumor 8 "

# variables that can directly be overwritten from CML
pwd_backup: "thisisasecret"
num_threads: 16
