run: '180614_SN737_0438_BCC7MCACXX'

directions:
  - 'R1'
  - 'R2'

emails_demultiplexreport: "stefan.m.janssen@gmail.com"

name_program: "spike"

dirs:
  prefix: "/gpfs/project/jansses/"

  intermediate: "Intermediate/"
  inputs: "Inputs/"
  aggregation: "Aggregation/"
  reports: "Reports/"
  checks: "Checks/"
  references: "References/"

  samplesheets: "SampleSheets/"
  rawillumina: "Raw_Illumina/"
  benchmarks: "Benchmarks/"
  logs: "Logs/"

stepnames:
  demultiplex: "05_demultiplex"
  rejoin_samples: "10_rejoin_samples"
  trim: "15_trim"
  map: "25_map"
  nodup: "30_remove_pcr_duplicates"
  gatk_intervals: "35_gatk_intervals"
  gatk_realignment: "40_gatk_realign"
  gatk_recalibration: "45_gatk_recalibration"
  gatk_calling: "50_gatk_calling"

gatk:
  HaplotypeCallerQualityArguments: " -stand_call_conf 50.0 -stand_emit_conf 50.0 "
